<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="52752" started-at="2015-09-25T16:23:53Z" finished-at="2015-09-25T16:24:46Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="52752" started-at="2015-09-25T16:23:53Z" finished-at="2015-09-25T16:24:46Z">
      <class name="autotest.appautotest.testa">
        <test-method status="PASS" signature="setUp()[pri:0, instance:autotest.appautotest.testa@60c6f5b]" name="setUp" is-config="true" duration-ms="21447" started-at="2015-09-26T00:23:53Z" finished-at="2015-09-26T00:24:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="login()[pri:0, instance:autotest.appautotest.testa@60c6f5b]" name="login" duration-ms="28923" started-at="2015-09-26T00:24:15Z" finished-at="2015-09-26T00:24:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at base.AndroidApp.findElement(AndroidApp.java:229)
	at base.AndroidApp.findElement(AndroidApp.java:1)
	at core.UI.clickElement(UI.java:18)
	at base.AndroidApp.runTestCase(AndroidApp.java:389)
	at autotest.appautotest.testa.login(testa.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:autotest.appautotest.testa@60c6f5b]" name="tearDown" is-config="true" duration-ms="2365" started-at="2015-09-26T00:24:44Z" finished-at="2015-09-26T00:24:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- autotest.appautotest.testa -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
