<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="52839" started-at="2015-09-25T16:17:27Z" finished-at="2015-09-25T16:18:20Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="52839" started-at="2015-09-25T16:17:27Z" finished-at="2015-09-25T16:18:20Z">
      <class name="autotest.appautotest.testa">
        <test-method status="PASS" signature="setUp()[pri:0, instance:autotest.appautotest.testa@5abca1e0]" name="setUp" is-config="true" duration-ms="21678" started-at="2015-09-26T00:17:27Z" finished-at="2015-09-26T00:17:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="login()[pri:0, instance:autotest.appautotest.testa@5abca1e0]" name="login" duration-ms="27252" started-at="2015-09-26T00:17:49Z" finished-at="2015-09-26T00:18:16Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA['appPackage' and 'appActivity' are required.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: 'appPackage' and 'appActivity' are required.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:125)
	at io.appium.java_client.android.AndroidDriver.startActivity(AndroidDriver.java:174)
	at io.appium.java_client.android.AndroidDriver.startActivity(AndroidDriver.java:201)
	at base.AndroidApp.startActivity(AndroidApp.java:365)
	at base.AndroidApp.runTestCase(AndroidApp.java:450)
	at autotest.appautotest.testa.login(testa.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:autotest.appautotest.testa@5abca1e0]" name="tearDown" is-config="true" duration-ms="3891" started-at="2015-09-26T00:18:16Z" finished-at="2015-09-26T00:18:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- autotest.appautotest.testa -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
